Repository Yuseong-AllowancePayments/Yuseong_AllowancePayments_iPadOS, pull requests merged in 2023-10, with the labels that each got.

#5 🔀 :: (#3) manageView 퍼블리싱
  Projects/App/Sources/App/SceneDelegate.swift
  Projects/App/Sources/Scene/Manage/Component/ButtonCollectionView.swift
  Projects/App/Sources/Scene/Manage/Component/CategoryListView.swift
  Projects/App/Sources/Scene/Manage/Component/Cell/ButtonCollectionViewCell.swift
  Projects/App/Sources/Scene/Manage/Component/Cell/DataTableViewCell.swift
  Projects/App/Sources/Scene/Manage/Component/Cell/UnderLineSegmentedControlCell.swift
  Projects/App/Sources/Scene/Manage/Component/PaddingLabel.swift
  Projects/App/Sources/Scene/Manage/Component/UnderLineSegmentedControl.swift
  Projects/App/Sources/Scene/Manage/ManageViewController.swift
Labels: feat, UI

#6 🔀 :: (#4) 수당 선택, 신청서 작성 UI 퍼블리싱
  Projects/App/Sources/App/SceneDelegate.swift
  Projects/App/Sources/Base/BaseVC.swift
  Projects/App/Sources/Extension/UIButton.swift
  Projects/App/Sources/Scene/ApplicationForm/ApplyVC.swift
  Projects/App/Sources/Scene/ApplicationForm/ApplyViewController.swift
  Projects/App/Sources/Scene/Manage/Component/Cell/DataTableViewCell.swift
  Projects/App/Sources/Scene/Manage/ManageViewController.swift
  Projects/App/Sources/Scene/SelectType/SelectTypeViewController.swift
  Projects/Shared/DesignSystem/Resources/ImageAssets.xcassets/calendar.imageset/calendar.svg
  Projects/Shared/DesignSystem/Sources/Button/SelectTypeButton.swift
  Projects/Shared/DesignSystem/Sources/Extension/ApplyFieldView.swift
  Projects/Shared/DesignSystem/Sources/Font/Font+Pretendard.swift
  Projects/Shared/DesignSystem/Sources/TextField/ApplyTextField.swift
  Scripts/NeedleRunScript.sh
Labels: feat, refactor, UI

#8 🔀 :: (#7) Flow&DI 추가
  Projects/App/Resources/LaunchScreen.storyboard
  Projects/App/Sources/App/AppDI.swift
  Projects/App/Sources/App/AppDelegate.swift
  Projects/App/Sources/App/Flow/AppFlow.swift
  Projects/App/Sources/App/Flow/AppStepper.swift
  Projects/App/Sources/App/Flow/ApplyFlow.swift
  Projects/App/Sources/App/Flow/ManageFlow.swift
  Projects/App/Sources/App/Flow/SelectTypeFlow.swift
  Projects/App/Sources/App/Flow/YuseongAllowanceStep.swift
  Projects/App/Sources/App/SceneDelegate.swift
  Projects/App/Sources/Base/BaseNC.swift
  Projects/App/Sources/Base/BaseVC.swift
  Projects/App/Sources/Presentation/Base/BaseVC.swift
  Projects/App/Sources/Presentation/Base/BaseVM.swift
  Projects/App/Sources/Presentation/Extension/UIButton.swift
  Projects/App/Sources/Presentation/Scene/ApplicationForm/ApplyViewController.swift
  Projects/App/Sources/Presentation/Scene/ApplicationForm/ApplyViewModel.swift
  Projects/App/Sources/Presentation/Scene/LaunchScreen/LaunchScreenViewController.swift
  Projects/App/Sources/Presentation/Scene/Manage/Component/ButtonCollectionView.swift
  Projects/App/Sources/Presentation/Scene/Manage/Component/CategoryListView.swift
  Projects/App/Sources/Presentation/Scene/Manage/Component/Cell/ButtonCollectionViewCell.swift
  Projects/App/Sources/Presentation/Scene/Manage/Component/Cell/DataTableViewCell.swift
  Projects/App/Sources/Presentation/Scene/Manage/Component/Cell/UnderLineSegmentedControlCell.swift
  Projects/App/Sources/Presentation/Scene/Manage/Component/PaddingLabel.swift
  Projects/App/Sources/Presentation/Scene/Manage/Component/UnderLineSegmentedControl.swift
  Projects/App/Sources/Presentation/Scene/Manage/ManageViewController.swift
  Projects/App/Sources/Presentation/Scene/Manage/ManageViewModel.swift
  Projects/App/Sources/Presentation/Scene/SelectType/SelectTypeViewController.swift
  Projects/App/Sources/Presentation/Scene/SelectType/SelectTypeViewModel.swift
Labels: feat, refactor

#10 Manager SignIn UI Publishing
  Projects/App/Sources/App/AppDI.swift
  Projects/App/Sources/App/Flow/ManageFlow.swift
  Projects/App/Sources/App/Flow/ManagerSignInFlow.swift
  Projects/App/Sources/App/Flow/SelectTypeFlow.swift
  Projects/App/Sources/App/Flow/YuseongAllowanceStep.swift
  Projects/App/Sources/Presentation/Scene/LaunchScreen/LaunchScreenViewController.swift
  Projects/App/Sources/Presentation/Scene/ManagerSignIn/ManagerSignInViewController.swift
  Projects/App/Sources/Presentation/Scene/ManagerSignIn/ManagerSignInViewModel.swift
  Projects/App/Sources/Presentation/Scene/SelectType/SelectTypeViewController.swift
  Projects/App/Sources/Presentation/Scene/SelectType/SelectTypeViewModel.swift
  Projects/Core/Keychain/Sources/Project.swift
  Projects/Core/Keychain/Tests/Project.swift
  Projects/Domain/LocalDomain/Sources/Project.swift
  Projects/Domain/LocalDomain/Tests/Project.swift
  Projects/Feature/ApplyFeature/Sources/ApplyVC.swift
  Projects/Feature/ApplyFeature/Tests/Project.swift
  Projects/Feature/BaseFeature/Sources/Base/BaseNC.swift
  Projects/Feature/BaseFeature/Sources/Base/BaseVC.swift
  Projects/Feature/BaseFeature/Sources/Base/BaseVM.swift
  Projects/Feature/BaseFeature/Tests/Project.swift
  Projects/Feature/ManageFeature/Sources/Project.swift
  Projects/Feature/ManageFeature/Tests/Project.swift
  Projects/Shared/DesignSystem/Resources/ImageAssets.xcassets/Yuseong_Logo.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/ImageAssets.xcassets/invisible.imageset/invisible.svg
  Projects/Shared/DesignSystem/Resources/ImageAssets.xcassets/logo.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/ImageAssets.xcassets/logo.imageset/YuseongLogo.png
  Projects/Shared/DesignSystem/Resources/ImageAssets.xcassets/textLogo.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/ImageAssets.xcassets/textLogo.imageset/YuseongTextLogo.png
  Projects/Shared/DesignSystem/Sources/Image/Image.swift
  Projects/Shared/DesignSystem/Sources/TextField/ApplyTextField.swift
  XCConfig/ApplyFeature/DEV.xcconfig
  XCConfig/ApplyFeature/PROD.xcconfig
  XCConfig/ApplyFeature/STAGE.xcconfig
  XCConfig/BaseFeature/DEV.xcconfig
  XCConfig/BaseFeature/PROD.xcconfig
  XCConfig/BaseFeature/STAGE.xcconfig
  XCConfig/Keychain/DEV.xcconfig
  XCConfig/Keychain/PROD.xcconfig
  XCConfig/Keychain/STAGE.xcconfig
  XCConfig/LocalDomain/DEV.xcconfig
  XCConfig/LocalDomain/PROD.xcconfig
  XCConfig/LocalDomain/STAGE.xcconfig
  XCConfig/ManageFeature/DEV.xcconfig
  XCConfig/ManageFeature/PROD.xcconfig
  XCConfig/ManageFeature/STAGE.xcconfig
Labels: refactor, UI
